"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es" | "fr" | "ar" | "hi" | "ja" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    heroTitle: "ArenaMind AI",
    heroSubtitle: "The Future of Intelligent Stadium Operations.",
    launchPlatform: "Launch Platform",
    watchOverview: "Watch Overview",
    dashboard: "Dashboard",
    about: "About",
    commandCenter: "Command Center",
    smartMobility: "Smart Mobility",
    ecoIntelligence: "Eco Intelligence",
    digitalTwin: "Digital Twin",
    agents: "AI Agents",
    attendance: "Attendance",
    staffActive: "Staff Active",
    responseTime: "Response Time",
    incidents: "Incidents",
    liveIncidents: "Live Incidents",
    viewAll: "View All",
    searchIncidents: "Search incidents...",
    totalAttendance: "Total Attendance",
    activeIncidents: "Active Incidents",
    staffOnDuty: "Staff on Duty",
    avgEntryTime: "Avg. Entry Time",
    crowdInflow: "Crowd Inflow Analysis",
    venueHotspots: "Venue Hotspots",
    predictiveAnalytics: "Predictive Analytics",
    staffDeployment: "Staff Deployment",
    manageDeployment: "Manage Deployment",
    allIncidents: "All Incidents",
    close: "Close",
    foodAI: "Food & Beverage",
    security: "Security",
    medical: "Medical",
    sustainability: "Sustainability",
    transport: "Transport",
    vision: "Vision",
    architecture: "Architecture",
    challenge: "The Challenge",
    developer: "Developer",
    ratings: "User Ratings",
    feedback: "Feedback",
    submit: "Submit",
    operationalIntel: "Real-time operational intelligence & predictive monitoring.",
    fans: "Fans",
    alerts: "Alerts",
    total: "Total",
    active: "Active",
    standby: "Standby",
    login: "Login",
    logout: "Logout",
    helpCenter: "Help Center",
    emergency: "Emergency",
    closeMenu: "Close",
    visitorsAssisted: "Visitors Assisted",
    aiDecisions: "AI Decisions/min",
    safetyRating: "Safety Rating",
    crowdDensity: "Crowd Density",
    securityAlert: "Security Alert",
    activeLanguages: "Active Languages",
    mission: "Mission",
    problemStatement: "Problem Statement",
    futureRoadmap: "Future Roadmap",
    copilotBadge: "AI MATCHDAY COPILOT",
    copilotTitle: "Your Personal",
    copilotTitleHighlight: "Tournament Guide.",
    copilotSubtitle: "Upload your ticket or enter your details, and our AI will generate a personalized end-to-end matchday itinerary tailored to your needs.",
    ticketID: "Ticket ID / File",
    seatNumber: "Seat Number",
    preferredLanguage: "Preferred Language",
    arrivalTime: "Arrival Time",
    transportMethod: "Transport Method",
    foodPreferences: "Food Preferences",
    continueToPreferences: "Continue to Preferences",
    back: "Back",
    initializeCopilot: "Initialize AI Copilot",
    generatingItinerary: "Generating Itinerary...",
    matchdaySchedule: "Your Matchday Schedule",
    aiInsights: "AI Insights",
    downloadPDF: "Download PDF",
    planAnotherMatch: "Plan Another Match",
    ticketInfo: "Scanning your ticket allows us to automatically identify your gate, hospitality level, and entry times.",
    agentEcosystemTitle: "Multi-Agent",
    agentEcosystemHighlight: "AI Ecosystem",
    agentEcosystemSubtitle: "A collective of specialized AI agents working in harmony to manage every aspect of stadium operations.",
    activeReasoning: "Active Reasoning",
    neuralOutput: "Neural Output",
    confidenceLevel: "Confidence Level",
    certaintyIndex: "Certainty Index",
    recentTaskLogs: "Recent Task Logs",
    neuralSynergy: "Neural Synergy",
    latency: "Latency",
    activeNodes: "Active Nodes",
    crossAgentSync: "Cross-agent synchronization",
    realTimeProcessing: "Real-time processing speed",
    sensorNetwork: "Distributed sensor network",
    metro: "Metro",
    carParking: "Car / Parking",
    rideShare: "Ride Share",
    walking: "Walking",
    noPreference: "No Preference",
    vegetarian: "Vegetarian",
    halal: "Halal",
    glutenFree: "Gluten Free",
    arenaVerse: "ArenaVerse 3D",
    launch: "Launch",
    demo: "Demo",
    home: "Home",
    features: "Features",
    pricing: "Pricing",
    contact: "Contact",
    register: "Register",
    fifaDetails: "FIFA 2026",
    exploreGlobe: "Explore Global Host Cities",
    stadiumSimulation: "Ultra-Realistic Stadium Simulation",
    liveMatchExperience: "Live Match Atmosphere",
    matchAnalytics: "Real-time Match Analytics",
    aiPredictor: "AI Match Predictor",
    voiceCommand: "Voice Command Active",
    photoMode: "Photo Mode",
    tourGuide: "AI Tour Guide",
  },
  es: {
    heroTitle: "ArenaMind AI",
    heroSubtitle: "El Futuro de las Operaciones Inteligentes en Estadios.",
    launchPlatform: "Iniciar Plataforma",
    watchOverview: "Ver Resumen",
    dashboard: "Panel",
    agents: "Agentes AI",
    digitalTwin: "Gemelo Digital",
    about: "Acerca de",
    commandCenter: "Centro de Mando",
    smartMobility: "Movilidad Inteligente",
    ecoIntelligence: "Eco Inteligencia",
    attendance: "Asistencia",
    staffActive: "Personal Activo",
    responseTime: "Tiempo de Respuesta",
    incidents: "Incidentes",
    liveIncidents: "Incidentes en Vivo",
    viewAll: "Ver Todo",
    searchIncidents: "Buscar incidentes...",
    totalAttendance: "Asistencia Total",
    activeIncidents: "Incidentes Activos",
    staffOnDuty: "Personal de Servicio",
    avgEntryTime: "Tiempo Promedio de Entrada",
    crowdInflow: "Análisis de Flujo de Multitud",
    venueHotspots: "Puntos Calientes del Lugar",
    predictiveAnalytics: "Análisis Predictivo",
    staffDeployment: "Despliegue de Personal",
    manageDeployment: "Gestionar Despliegue",
    allIncidents: "Todos los Incidentes",
    close: "Cerrar",
    foodAI: "Alimentos y Bebidas",
    security: "Seguridad",
    medical: "Médico",
    sustainability: "Sostenibilidad",
    transport: "Transporte",
    vision: "Visión",
    architecture: "Arquitectura",
    challenge: "El Desafío",
    developer: "Desarrollador",
    ratings: "Calificaciones",
    feedback: "Comentarios",
    submit: "Enviar",
    operationalIntel: "Inteligencia operativa en tiempo real y monitoreo predictivo.",
    fans: "Fans",
    alerts: "Alertas",
    total: "Total",
    active: "Activo",
    standby: "En Espera",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    helpCenter: "Centro de Ayuda",
    emergency: "Emergencia",
    closeMenu: "Cerrar",
    visitorsAssisted: "Visitantes Asistidos",
    aiDecisions: "Decisiones AI/min",
    safetyRating: "Calificación de Seguridad",
    crowdDensity: "Densidad de Multitud",
    securityAlert: "Alerta de Seguridad",
    activeLanguages: "Idiomas Activos",
    copilotBadge: "COPILOTO DE PARTIDO AI",
    copilotTitle: "Tu Guía",
    copilotTitleHighlight: "Personal del Torneo.",
    copilotSubtitle: "Sube tu entrada o ingresa tus datos, y nuestra IA generará un itinerario personalizado para tu día de partido.",
    ticketID: "ID de Entrada / Archivo",
    seatNumber: "Número de Asiento",
    preferredLanguage: "Idioma Preferido",
    arrivalTime: "Hora de Llegada",
    transportMethod: "Método de Transporte",
    foodPreferences: "Preferencias de Comida",
    continueToPreferences: "Continuar a Preferencias",
    back: "Atrás",
    initializeCopilot: "Iniciar Copiloto AI",
    generatingItinerary: "Generando Itinerario...",
    matchdaySchedule: "Tu Horario del Partido",
    aiInsights: "Perspectivas de IA",
    downloadPDF: "Descargar PDF",
    planAnotherMatch: "Planificar otro Partido",
    ticketInfo: "Escanear tu entrada nos permite identificar automáticamente tu puerta, nivel de hospitalidad y horarios de entrada.",
    agentEcosystemTitle: "Ecosistema de",
    agentEcosystemHighlight: "IA Agentes",
    agentEcosystemSubtitle: "Un colectivo de agentes de IA especializados que trabajan en armonía para gestionar cada aspecto de las operaciones del estadio.",
    activeReasoning: "Razonamiento Activo",
    neuralOutput: "Salida Neuronal",
    confidenceLevel: "Nivel de Confianza",
    certaintyIndex: "Índice de Certeza",
    recentTaskLogs: "Registros de Tareas Recientes",
    neuralSynergy: "Sinergia Neuronal",
    latency: "Latencia",
    activeNodes: "Nodos Activos",
    crossAgentSync: "Sincronización entre agentes",
    realTimeProcessing: "Velocidad de procesamiento en tiempo real",
    sensorNetwork: "Red de sensores distribuida",
    metro: "Metro",
    carParking: "Coche / Estacionamiento",
    rideShare: "Viaje Compartido",
    walking: "Caminando",
    noPreference: "Sin Preferencia",
    vegetarian: "Vegetariano",
    halal: "Halal",
    glutenFree: "Sin Gluten",
    arenaVerse: "ArenaVerse 3D",
    fifaDetails: "FIFA 2026",
    exploreGlobe: "Explorar Ciudades Anfitrionas Globales",
    stadiumSimulation: "Simulación de Estadio Ultra Realista",
    liveMatchExperience: "Atmósfera de Partido en Vivo",
    matchAnalytics: "Analítica de Partido en Tiempo Real",
    aiPredictor: "Predictor de Partidos AI",
    voiceCommand: "Comando de Voz Activo",
    photoMode: "Modo Foto",
    tourGuide: "Guía Turístico AI",
  },
  hi: {
    heroTitle: "एरिनामाइंड AI",
    heroSubtitle: "बुद्धिमान स्टेडियम संचालन का भविष्य।",
    launchPlatform: "प्लेटफॉर्म लॉन्च करें",
    watchOverview: "अवलोकन देखें",
    dashboard: "डैशबोर्ड",
    agents: "AI एजेंट",
    digitalTwin: "डिजिटल ट्विन",
    about: "बारे में",
    commandCenter: "कमांड सेंटर",
    smartMobility: "स्मार्ट मोबिलिटी",
    ecoIntelligence: "इको इंटेलिजेंस",
    attendance: "उपस्थिति",
    staffActive: "सक्रिय कर्मचारी",
    responseTime: "प्रतिक्रिया समय",
    incidents: "घटनाएं",
    liveIncidents: "लाइव घटनाएं",
    viewAll: "सभी देखें",
    searchIncidents: "घटनाएं खोजें...",
    totalAttendance: "कुल उपस्थिति",
    activeIncidents: "सक्रिय घटनाएं",
    staffOnDuty: "ड्यूटी पर कर्मचारी",
    avgEntryTime: "औसत प्रवेश समय",
    crowdInflow: "भीड़ प्रवाह विश्लेषण",
    venueHotspots: "स्थान हॉटस्पॉट",
    predictiveAnalytics: "पूर्वानुमानित विश्लेषण",
    staffDeployment: "कर्मचारी तैनाती",
    manageDeployment: "तैनाती प्रबंधित करें",
    allIncidents: "सभी घटनाएं",
    close: "बंद करें",
    foodAI: "खाद्य और पेय",
    security: "सुरक्षा",
    medical: "चिकित्सा",
    sustainability: "सततता",
    transport: "परिवहन",
    vision: "दृष्टि",
    architecture: "स्थापत्य",
    challenge: "चुनौती",
    developer: "डेवलपर",
    ratings: "रेटिंग",
    feedback: "प्रतिक्रिया",
    submit: "जमा करें",
    operationalIntel: "वास्तविक समय परिचालन खुफिया और पूर्वानुमानित निगरानी।",
    fans: "प्रशंसक",
    alerts: "अलर्ट",
    total: "कुल",
    active: "सक्रिय",
    standby: "स्टैंडबाय",
    login: "लॉगिन",
    logout: "लॉगआउट",
    helpCenter: "सहायता केंद्र",
    emergency: "आपातकालीन",
    closeMenu: "बंद करें",
    visitorsAssisted: "सहायता प्राप्त आगंतुक",
    aiDecisions: "AI निर्णय/मिनट",
    safetyRating: "सुरक्षा रेटिंग",
    crowdDensity: "भीड़ घनत्व",
    securityAlert: "सुरक्षा अलर्ट",
    activeLanguages: "सक्रिय भाषाएं",
    copilotBadge: "AI मैचडे कोपायलट",
    copilotTitle: "आपका व्यक्तिगत",
    copilotTitleHighlight: "टूर्नामेंट गाइड।",
    copilotSubtitle: "अपना टिकट अपलोड करें या अपना विवरण दर्ज करें, और हमारा AI आपकी आवश्यकताओं के अनुरूप एक व्यक्तिगत मैचडे यात्रा कार्यक्रम तैयार करेगा।",
    ticketID: "टिकट आईडी / फ़ाइल",
    seatNumber: "सीट संख्या",
    preferredLanguage: "पसंदीदा भाषा",
    arrivalTime: "आगमन का समय",
    transportMethod: "परिवहन विधि",
    foodPreferences: "भोजन प्राथमिकताएं",
    continueToPreferences: "प्राथमिकताओं पर जारी रखें",
    back: "पीछे",
    initializeCopilot: "AI कोपायलट शुरू करें",
    generatingItinerary: "यात्रा कार्यक्रम तैयार किया जा रहा है...",
    matchdaySchedule: "आपका मैचडे शेड्यूल",
    aiInsights: "AI अंतर्दृष्टि",
    downloadPDF: "PDF डाउनलोड करें",
    planAnotherMatch: "दूसरे मैच की योजना बनाएं",
    ticketInfo: "आपका टिकट स्कैन करने से हमें आपके गेट, आतिथ्य स्तर और प्रवेश समय की स्वचालित रूप से पहचान करने में मदद मिलती है।",
    agentEcosystemTitle: "मल्टी-एजेंट",
    agentEcosystemHighlight: "AI इकोसिस्टम",
    agentEcosystemSubtitle: "स्टेडियम संचालन के हर पहलू को प्रबंधित करने के लिए सद्भाव में काम करने वाले विशेष AI एजेंटों का एक समूह।",
    activeReasoning: "सक्रिय तर्क",
    neuralOutput: "तंत्रिका आउटपुट",
    confidenceLevel: "आत्मविश्वास का स्तर",
    certaintyIndex: "निश्चितता सूचकांक",
    recentTaskLogs: "हालिया कार्य लॉग",
    neuralSynergy: "तंत्रिका तालमेल",
    latency: "विलंबता",
    activeNodes: "सक्रिय नोड्स",
    crossAgentSync: "क्रॉस-एजेंट सिंक्रनाइज़ेशन",
    realTimeProcessing: "वास्तविक समय प्रसंस्करण गति",
    sensorNetwork: "वितरित सेंसर नेटवर्क",
    metro: "मेट्रो",
    carParking: "कार / पार्किंग",
    rideShare: "राइड शेयर",
    walking: "पैदल",
    noPreference: "कोई प्राथमिकता नहीं",
    vegetarian: "शाकाहारी",
    halal: "हलाल",
    glutenFree: "ग्लूटेन मुक्त",
    arenaVerse: "एरीनावर्स 3D",
    exploreGlobe: "वैश्विक मेजबان शहरों का अन्वेषण करें",
    stadiumSimulation: "अल्ट्रा-यथार्थवादी स्टेडियम सिमुलेशन",
    liveMatchExperience: "लाइव मैच का माहौल",
    matchAnalytics: "वास्तविक समय मैच विश्लेषण",
    aiPredictor: "AI मैच भविष्यवक्ता",
    voiceCommand: "वॉयस कमांड सक्रिय",
    photoMode: "फोटो मोड",
    tourGuide: "AI टूर गाइड",
  },

  ar: {
    heroTitle: "أرينا مايند AI",
    heroSubtitle: "مستقبل عمليات الملاعب الذكية.",
    launchPlatform: "إطلاق المنصة",
    watchOverview: "شاهد العرض",
    dashboard: "لوحة القيادة",
    agents: "وكلاء الذكاء الاصطناعي",
    digitalTwin: "التوأم الرقمي",
    about: "حول",
  },
  fr: {
    heroTitle: "ArenaMind AI",
    heroSubtitle: "L'avenir des opérations de stade intelligentes.",
    launchPlatform: "Lancer la plateforme",
    watchOverview: "Voir l'aperçu",
    dashboard: "Tableau de bord",
    agents: "Agents IA",
    digitalTwin: "Jumeau numérique",
    about: "À propos",
  },
  ja: {
    heroTitle: "ArenaMind AI",
    heroSubtitle: "インテリジェントなスタジアム運営の未来。",
    launchPlatform: "プラットフォームを起動",
    watchOverview: "概要を見る",
    dashboard: "ダッシュボード",
    agents: "AIエージェント",
    digitalTwin: "デジタルツイン",
    about: "詳細",
  },
  pt: {
    heroTitle: "ArenaMind AI",
    heroSubtitle: "O futuro das operações inteligentes em estádios.",
    launchPlatform: "Lançar plataforma",
    watchOverview: "Ver visão geral",
    dashboard: "Painel",
    agents: "Agentes de IA",
    digitalTwin: "Gêmeo Digital",
    about: "Sobre",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  React.useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
